/**
 * CSS snippet generation.
 *
 * Custom callout types have to survive the plugin being disabled and have to
 * beat theme rules, so they are written to a real snippet in the vault rather
 * than injected at runtime. Snippets load after themes, which is exactly the
 * cascade position custom types need.
 */

import { Notice } from 'obsidian';
import type { App } from 'obsidian';
import type { CustomCalloutType, CustomIcon } from '../types';
import { hexToCssColor } from './colors';
import { svgToCssValue } from './svg';

export const SNIPPET_NAME = 'callout-customizer';
const SNIPPET_FILE = `${SNIPPET_NAME}.css`;

const HEADER = [
	'/*',
	' * Generated by the Callout Customizer plugin.',
	' *',
	' * Edits here are overwritten whenever a custom callout type changes.',
	' * To keep changes, copy them into a different snippet file.',
	' */',
	'',
].join('\n');

/** Obsidian's snippet registry. Not part of the public API. */
interface CustomCssLike {
	setCssEnabledStatus?: (name: string, enabled: boolean) => void;
	enabledSnippets?: Set<string>;
	requestLoadSnippets?: () => void;
}

export class SnippetWriter {
	constructor(private readonly app: App) {}

	private get folder(): string {
		return `${this.app.vault.configDir}/snippets`;
	}

	private get path(): string {
		return `${this.folder}/${SNIPPET_FILE}`;
	}

	/** Rewrite the snippet from the current custom types and icons. */
	async write(types: readonly CustomCalloutType[], icons: readonly CustomIcon[]): Promise<void> {
		const { adapter } = this.app.vault;

		if (!(await adapter.exists(this.folder))) {
			await adapter.mkdir(this.folder);
		}

		await adapter.write(this.path, HEADER + this.buildCss(types, icons));
		this.reload();
	}

	async exists(): Promise<boolean> {
		return this.app.vault.adapter.exists(this.path);
	}

	isEnabled(): boolean {
		const customCss = this.customCss();
		return customCss?.enabledSnippets?.has(SNIPPET_NAME) ?? false;
	}

	/**
	 * Turn the snippet on. Uses an internal API, so failure is reported rather
	 * than thrown - the user can always enable it by hand.
	 */
	enable(): boolean {
		const customCss = this.customCss();

		if (typeof customCss?.setCssEnabledStatus !== 'function') {
			new Notice(
				'Could not enable the snippet automatically. Turn on "callout-customizer" in Settings → Appearance → CSS snippets.',
				10_000,
			);
			return false;
		}

		customCss.setCssEnabledStatus(SNIPPET_NAME, true);
		return true;
	}

	private reload(): void {
		this.customCss()?.requestLoadSnippets?.();
	}

	private customCss(): CustomCssLike | undefined {
		return (this.app as App & { customCss?: CustomCssLike }).customCss;
	}

	private buildCss(
		types: readonly CustomCalloutType[],
		icons: readonly CustomIcon[],
	): string {
		const blocks: string[] = [];

		for (const type of types) {
			const declarations: string[] = [];

			if (type.color) {
				declarations.push(`\t--callout-color: ${hexToCssColor(type.color)};`);
			}
			if (type.icon) {
				const icon = icons.find((candidate) => `svg-${candidate.slug}` === type.icon);
				declarations.push(
					icon
						? `\t--callout-icon: ${svgToCssValue(icon.svg)};`
						: `\t--callout-icon: lucide-${type.icon};`,
				);
			}

			if (!declarations.length) continue;

			blocks.push(
				`/* ${type.name} */\n.callout[data-callout="${type.id}"] {\n${declarations.join('\n')}\n}`,
			);
		}

		if (!blocks.length) {
			blocks.push('/* No custom callout types saved yet. */');
		}

		return blocks.join('\n\n') + '\n';
	}
}
